In [1]:
import pandas as pd
import numpy as np
from datetime import timedelta

# Load data
csv_file_path = "/Users/balmeru/Downloads/median_fyrchange_dates.csv"
df = pd.read_csv(csv_file_path)
df['rdq'] = pd.to_datetime(df['rdq'], errors='coerce')

df['txdbq'] = df['txdbq'].fillna(0)
df['dvpq'] = df['dvpq'].fillna(0)

df.loc[:, "income_good"] = False
df.loc[~df["ibq"].isna(), "income_good"] = True

#1
df.loc[:, "se1_good"] = False
df.loc[~df["teqq"].isna(), "se1_good"] = True

#2
df.loc[:, "se2_good"] = False
df.loc[~df["ceqq"].isna() & ~df["pstkq"].isna(), "se2_good"] = True

#3
df.loc[:, "se3_good"] = False
df.loc[~df["atq"].isna() & ~df["ltq"].isna(), "se3_good"] = True


# Filter out cases where fyr_change is False and conditions for income_good and se goods are met
df_filtered = df[(df['income_good'] == True) & ((df['se1_good'] == True) | (df['se2_good'] == True) | (df['se3_good'] == True))]
target_year = 1986
reference_year = 1985
expected_dates = []
for tic in df_filtered['tic'].unique():
    tic_data = df_filtered[
        (df_filtered['tic'] == tic) & 
        (df_filtered['fyearq'] == reference_year)
    ]  
    for quarter in range(1, 5):
        quarter_data = tic_data[
            (tic_data['fqtr'] == quarter)
        ]
        
        if not quarter_data.empty:
            reference_date = quarter_data['rdq'].iloc[0]
            expected_date = reference_date + timedelta(weeks=52)
        else:
            expected_date = np.nan  
        
        expected_dates.append({
            'quarter': f"1986Q{quarter}",  
            'tic': tic,                   
            'expected_announcement_date': expected_date  
        })
expected_dates_df = pd.DataFrame(expected_dates)
expected_dates_df['quarter'] = pd.Categorical(expected_dates_df['quarter'], categories=['1986Q1', '1986Q2', '1986Q3', '1986Q4'], ordered=True)

pivot_table = expected_dates_df.pivot_table(
    index='quarter',   
    columns='tic',    
    values='expected_announcement_date'  
)

pivot_table_cleaned = pivot_table.dropna(axis=1, how='all')
print("Pivot Table corrected for both early and late reporting:")
print(pivot_table_cleaned)

Pivot Table corrected for both early and late reporting:
tic          0015B      0033A      0053A      0131A      0141A      0170A  \
quarter
1986Q1  1986-03-04 1986-04-28        NaT 1986-04-25 1986-04-18 1986-05-15
1986Q2  1986-06-16 1986-07-28        NaT 1986-07-29 1986-07-29 1986-08-15
1986Q3  1986-09-08 1986-10-27 1986-11-10 1986-10-29 1986-10-29 1986-11-13
1986Q4  1987-01-05 1987-02-23 1987-03-10 1987-02-02 1987-01-29 1987-03-20

tic          0173A      0223B      0410B      0419B  ...       ZIAD  \
quarter                                              ...
1986Q1  1986-08-19 1986-04-30        NaT        NaT  ... 1986-06-24
1986Q2  1986-11-19 1986-07-28 1986-07-30        NaT  ... 1986-09-23
1986Q3  1987-02-18 1986-10-30 1986-10-30        NaT  ... 1986-12-22
1986Q4  1987-05-29 1987-02-11 1987-02-10 1987-02-27  ... 1987-04-21

tic           ZIGO      ZIM.1       ZION        ZLC        ZMX       ZOND  \
quarter
1986Q1  1985-11-05 1986-05-07 1986-04-16 1986-07-16 1986-04-25 1986-05-20
1986Q2  1986-02-03 1986-07-29 1986-07-15 1986-10-21 1986-07-23 1986-08-12
1986Q3  1986-05-08 1986-10-21 1986-10-20 1987-01-15 1986-10-28 1986-11-05
1986Q4  1986-08-25 1987-03-03 1987-01-27 1987-05-15 1987-02-12 1987-03-25

tic           ZRBA        ZRN        ZRO
quarter
1986Q1  1986-06-23 1986-07-17 1986-07-17
1986Q2  1986-09-22 1986-10-15 1986-10-17
1986Q3  1986-12-22 1987-01-14 1987-01-26
1986Q4  1987-04-22 1987-05-26 1987-05-08

[4 rows x 4357 columns]

In [2]:
pivot_table_cleaned.to_csv('expected_dates_1986.csv', index=True)